const data = {
  date: "2027-04-03T15:00:00",
  rsvp: "#",
  footerDate: "03 aprile 2027",
  churchMap: "https://maps.app.goo.gl/ScvbSA8MKmW7madm6",
  venueMap: "https://maps.app.goo.gl/GaUVYHBnTdK6obdK8",
  fr: {
    nav: { home: "Home", rsvp: "RSVP", info: "Info", stay: "Séjour", gifts: "Liste", about: "Nous" },
    subtitle: "03 avril 2027 • Luogo",
    rsvpEyebrow: "Répondre",
    rsvpTitle: "Serez-vous là ?",
    rsvpSub: "Faites-nous savoir.",
    rsvpBtn: "Confirmer",
    infoTitle: "Informations",
    churchLabel: "Cérémonie",
    churchAddress: "Chiesa — indirizzo",
    churchTime: "15:00",
    accessNote: ["Nota accesso 1","Nota accesso 2"],
    venueLabel: "Réception",
    venue: "Luogo della festa",
    stayLabel: "Hébergement",
    howToGet: "Comment arriver",
    trenord: "Acheter les billets →",
    giftsTitle: "Liste de mariage",
    giftIntro: "Lista nozze",
    aboutTitle: "Les mariés",
    aboutSub: "Clique sur la photo",
    about: "Siamo felici!"
  },
  it: {
    nav: { home: "Home", rsvp: "RSVP", info: "Info", stay: "Arrivo", gifts: "Lista", about: "Noi" },
    subtitle: "03 aprile 2027 • Luogo",
    rsvpEyebrow: "Rispondere",
    rsvpTitle: "Ci sarai?",
    rsvpSub: "Facci sapere.",
    rsvpBtn: "Confermare",
    infoTitle: "Informazioni",
    churchLabel: "Celebrazione",
    churchAddress: "Chiesa — indirizzo",
    churchTime: "15:00",
    accessNote: ["Nota accesso 1","Nota accesso 2"],
    venueLabel: "Ricevimento",
    venue: "Luogo della festa",
    stayLabel: "Pernottamento",
    howToGet: "Come arrivare",
    trenord: "Acquista i biglietti →",
    giftsTitle: "Lista nozze",
    giftIntro: "Lista nozze",
    aboutTitle: "Gli sposi",
    aboutSub: "Clicca sulla foto",
    about: "Non vediamo l'ora di festeggiare!"
  },
  gifts: [],
  hotels: []
};
