const data = {
  date:        "2027-04-03T15:00:00",
  rsvp:        "#",
  footerDate:  "03.04.2027",

  churchMap: "https://maps.google.com/maps/search/?api=1&query=Basilica+di+Santa+Maria+in+Domnica+alla+Navicella+Roma",
  venueMap:  "https://maps.google.com/maps/search/?api=1&query=Roma",
  trenord:   "https://www.trenitalia.com/",

  // ── ITALIANO (default) ──────────────────
  it: {
    nav: {
      home: "Home",
      when: "Dove e quando",
      travel: "Raggiungerci",
      couple: "Gli sposi",
      gift: "Lista nozze",
      rsvp: "RSVP",
      quote: "Citazione",
      lang: "Lingua",
    },

    heroDate: "03.04.2027",
    heroPlace: "Basilica di Santa Maria in Domnica alla Navicella",
    heroSwipeHint: "‹ scorri ›",

    whenSub: "Dove e quando",
    whenTitle: "Dove e quando",
    churchLabel: "Cerimonia",
    churchName: "Basilica di Santa Maria in Domnica alla Navicella, Roma",
    churchTime: "ore 15:00",
    venueLabel: "Ricevimento",
    venueName: "Placeholder: luogo del ricevimento, Roma",
    viewMap: "Vedi sulla mappa",

    travelSub: "Raggiungerci",
    travelTitle: "Come arrivare a Roma",
    fromFiumicino: "✈️ Aeroporto Fiumicino",
    fromMilan: "🏙️ Milano",
    optTrainDirect: "🚆 Treno diretto Leonardo → Roma Termini",
    duration32: "~32 min",
    optBusDirect: "🚌 Bus diretto → Roma Termini",
    duration50: "~50 min",
    optTav: "🚆 Treno ad alta velocità → Roma Termini",
    duration3h: "~3h",
    optCar: "🚘 In auto → Roma",
    duration6h: "~6h",
    trenordLink: "Acquista i biglietti su Trenitalia →",
    hotelsTitle: "Dove dormire",
    fromPrice: "da {price} € / notte",
    siteLink: "Sito",
    mapLink: "Mappa",

    coupleSub: "Gli sposi",
    coupleTitle: "Gli sposi",
    coupleBody: "Ci siamo incontrati e da quel giorno la strada si è fatta più luminosa. Ecco come è iniziata la nostra storia.",
    couplePhoto1Alt: "Placeholder: foto del primo incontro",
    couplePhoto1Caption: "dove tutto è iniziato",
    couplePhoto2Alt: "Placeholder: foto della proposta",
    couplePhoto2Caption: "il sì è stato detto",

    giftTitle: "Lista nozze",
    giftIntro: "Se desiderate aiutarci a iniziare questo nuovo capitolo, potete regalarci uno degli oggetti qui sotto oppure contribuire al nostro viaggio di nozze in Giappone ❤️",
    swipeHint: "‹ swipe ›",

    rsvpSub: "RSVP",
    rsvpTitle: "Sarai dei nostri?",
    rsvpBody: "Facci sapere entro il 3 marzo 2027 se potrai camminare con noi in questo giorno.",
    rsvpBtn: "Conferma la presenza",

    quote: "Not all those who wander are lost",
  },

  // ── FRANÇAIS ────────────────────────────
  fr: {
    nav: {
      home: "Accueil",
      when: "Où et quand",
      travel: "Venir",
      couple: "Les mariés",
      gift: "Liste de mariage",
      rsvp: "RSVP",
      quote: "Citation",
      lang: "Langue",
    },

    heroDate: "03.04.2027",
    heroPlace: "Basilique Santa Maria in Domnica alla Navicella",
    heroSwipeHint: "‹ balayer ›",

    whenSub: "Où et quand",
    whenTitle: "Où et quand",
    churchLabel: "Cérémonie",
    churchName: "Basilique Santa Maria in Domnica alla Navicella, Rome",
    churchTime: "15h00",
    venueLabel: "Réception",
    venueName: "Placeholder : lieu de réception, Rome",
    viewMap: "Voir sur la carte",

    travelSub: "Venir",
    travelTitle: "Comment arriver à Rome",
    fromFiumicino: "✈️ Aéroport Fiumicino",
    fromMilan: "🏙️ Milan",
    optTrainDirect: "🚆 Train direct Leonardo → Roma Termini",
    duration32: "~32 min",
    optBusDirect: "🚌 Bus direct → Roma Termini",
    duration50: "~50 min",
    optTav: "🚆 Train à grande vitesse → Roma Termini",
    duration3h: "~3h",
    optCar: "🚘 En voiture → Rome",
    duration6h: "~6h",
    trenordLink: "Acheter les billets sur Trenitalia →",
    hotelsTitle: "Où dormir",
    fromPrice: "dès {price} € / nuit",
    siteLink: "Site",
    mapLink: "Carte",

    coupleSub: "Les mariés",
    coupleTitle: "Les mariés",
    coupleBody: "Nous nous sommes rencontrés et depuis ce jour le chemin est devenu plus lumineux. Voici comment notre histoire a commencé.",
    couplePhoto1Alt: "Placeholder : photo de la première rencontre",
    couplePhoto1Caption: "où tout a commencé",
    couplePhoto2Alt: "Placeholder : photo de la demande",
    couplePhoto2Caption: "le oui a été dit",

    giftTitle: "Liste de mariage",
    giftIntro: "Si vous souhaitez nous aider à commencer ce nouveau chapitre, vous pouvez nous offrir l'un des objets ci-dessous ou contribuer à notre voyage de noces au Japon ❤️",
    swipeHint: "‹ swipe ›",

    rsvpSub: "RSVP",
    rsvpTitle: "Serez-vous là ?",
    rsvpBody: "Faites-nous savoir avant le 3 mars 2027 si vous pourrez marcher avec nous ce jour-là.",
    rsvpBtn: "Confirmer sa présence",

    quote: "Not all those who wander are lost",
  },

  // ── ENGLISH ─────────────────────────────
  en: {
    nav: {
      home: "Home",
      when: "Where & when",
      travel: "Getting there",
      couple: "The couple",
      gift: "Gift list",
      rsvp: "RSVP",
      quote: "Quote",
      lang: "Language",
    },

    heroDate: "03.04.2027",
    heroPlace: "Basilica di Santa Maria in Domnica alla Navicella",
    heroSwipeHint: "‹ swipe ›",

    whenSub: "Where & when",
    whenTitle: "Where & when",
    churchLabel: "Ceremony",
    churchName: "Basilica di Santa Maria in Domnica alla Navicella, Rome",
    churchTime: "3:00 pm",
    venueLabel: "Reception",
    venueName: "Placeholder: reception venue, Rome",
    viewMap: "View on map",

    travelSub: "Getting there",
    travelTitle: "How to reach Rome",
    fromFiumicino: "✈️ Fiumicino Airport",
    fromMilan: "🏙️ Milan",
    optTrainDirect: "🚆 Direct Leonardo train → Roma Termini",
    duration32: "~32 min",
    optBusDirect: "🚌 Direct bus → Roma Termini",
    duration50: "~50 min",
    optTav: "🚆 High-speed train → Roma Termini",
    duration3h: "~3h",
    optCar: "🚘 By car → Rome",
    duration6h: "~6h",
    trenordLink: "Buy tickets on Trenitalia →",
    hotelsTitle: "Where to stay",
    fromPrice: "from {price} € / night",
    siteLink: "Site",
    mapLink: "Map",

    coupleSub: "The couple",
    coupleTitle: "The couple",
    coupleBody: "We met, and from that day the road has been brighter. Here is how our story began.",
    couplePhoto1Alt: "Placeholder: photo of our first meeting",
    couplePhoto1Caption: "where it all began",
    couplePhoto2Alt: "Placeholder: photo of the proposal",
    couplePhoto2Caption: "the yes was said",

    giftTitle: "Gift list",
    giftIntro: "If you'd like to help us start this new chapter, you can gift us one of the items below or contribute to our honeymoon in Japan ❤️",
    swipeHint: "‹ swipe ›",

    rsvpSub: "RSVP",
    rsvpTitle: "Will you be there?",
    rsvpBody: "Let us know by March 3, 2027 if you'll walk with us on this day.",
    rsvpBtn: "Confirm attendance",

    quote: "Not all those who wander are lost",
  },

  // ── Shared data (not translated) ─────────
  gifts: [
    { name: "Viaggio di nozze in Giappone",  nameFr: "Voyage de noces au Japon",  nameEn: "Honeymoon in Japan",    price: 1200, icon: "✈️", photo: "assets/images/placeholder-gift-honeymoon.svg", hidePrice: true },
    { name: "Giradischi e vinili — Placeholder", nameFr: "Tourne-disque et vinyles — Placeholder", nameEn: "Turntable and vinyls — Placeholder", price: 300, icon: "🎵", photo: "assets/images/placeholder-gift-vinyl.svg" },
    { name: "Proiettore — Placeholder",      nameFr: "Projecteur — Placeholder", nameEn: "Projector — Placeholder", price: 600, icon: "🎬", photo: "assets/images/placeholder-gift-projector.svg" },
    { name: "Macchina da caffè — Placeholder", nameFr: "Machine à café — Placeholder", nameEn: "Coffee machine — Placeholder", price: 200, icon: "☕", photo: "assets/images/placeholder-gift-coffee.svg" },
    { name: "Set di pentole — Placeholder",  nameFr: "Set de casseroles — Placeholder", nameEn: "Cookware set — Placeholder", price: 250, icon: "🍳", photo: "assets/images/placeholder-gift-cookware.svg" },
  ],

  hotels: [
    { icon: "🏨", name: "Placeholder: Hotel 1", location: "Roma",  price: 150, website: "https://example.com", map: "https://maps.google.com" },
    { icon: "🛏️", name: "Placeholder: B&B 1",   location: "Roma",  price: 90,  website: "https://example.com", map: "https://maps.google.com" },
    { icon: "🏡", name: "Placeholder: Affitto 1", location: "Roma", price: 120, website: "https://example.com", map: "https://maps.google.com" },
    { icon: "🌿", name: "Placeholder: Agriturismo", location: "Roma", price: 110, website: "https://example.com", map: "https://maps.google.com" },
  ],
};